# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.3-pre-1
loader_version=0.19.5
# Mod Properties
mod_version=1.0-SNAPSHOT
maven_group=dev.lucachinou
archives_base_name=stoppausemymusic
minecraft_version_range=>=26.3-pre.1
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.159.1+26.3
# 26.3 uses a Fabric identity/intermediary mapping in build.gradle
